import './globals.css';
import { Inter, } from 'next/font/google';
import React from 'react';

const inter = Inter({ subsets: ['latin'], });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, }) {
	return (
		<html lang="en">
			<head>
				<link
					rel="preconnect"
					href="https://fonts.googleapis.com"/>
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;500;600;700&display=swap"
					rel="stylesheet"/>
				<title>From Roots to Global Success</title>
				<meta
					name="description"
					content="An exclusive online program catering to Romanians living and working abroad. Our program is specifically designed to help you leverage your cultural background to thrive professionally in diverse settings"
				/>
			</head>
			<body className={ inter.className }>{children}</body>
		</html>
	);
}
